-- Universidade Rottas — dados de exemplo (rodar depois do 01_schema.sql)
-- Os vídeos ainda não têm link do SharePoint: edite cada conteúdo no app e cole o código de incorporação.

insert into public.setores (nome, ordem) values ('Excelência Operacional', 0)
on conflict (nome) do nothing;
-- outros setores: cadastre em Gerenciar conteúdo > Setores

insert into public.trilhas (slug, nome, descricao, cor, cor2, ordem) values ('eng', 'Engenharia', 'Processos, sistemas e rotinas da engenharia de obras: ERP, BPMs, Mereo e atualização orçamentária.', '#E07A0B', '#FF9E2C', 0) on conflict (slug) do nothing;
insert into public.secoes (trilha_id, slug, nome, descricao, ordem) select id, 'eng-erp', 'ERP', 'Medições, contratos, aditivos e consultas no ERP.', 0 from public.trilhas where slug='eng' on conflict (slug) do nothing;
insert into public.secoes (trilha_id, slug, nome, descricao, ordem) select id, 'eng-bpm', 'BPMs', 'Fluxos de aprovação e solicitações no BPM.', 1 from public.trilhas where slug='eng' on conflict (slug) do nothing;
insert into public.secoes (trilha_id, slug, nome, descricao, ordem) select id, 'eng-mereo', 'Mereo', 'Metas, indicadores e ciclo de desempenho.', 2 from public.trilhas where slug='eng' on conflict (slug) do nothing;
insert into public.secoes (trilha_id, slug, nome, descricao, ordem) select id, 'eng-orc', 'Atualização orçamentária', 'Rodadas de reprojeção, premissas e curva S.', 3 from public.trilhas where slug='eng' on conflict (slug) do nothing;
insert into public.trilhas (slug, nome, descricao, cor, cor2, ordem) values ('sup', 'Suprimentos', 'Compras, contratação de terceiros e gestão de fornecedores.', '#3B3A39', '#6A6867', 1) on conflict (slug) do nothing;
insert into public.secoes (trilha_id, slug, nome, descricao, ordem) select id, 'sup-compras', 'Compras', 'Do pedido à entrega na obra.', 0 from public.trilhas where slug='sup' on conflict (slug) do nothing;
insert into public.secoes (trilha_id, slug, nome, descricao, ordem) select id, 'sup-contratos', 'Contratos', 'Minutas, assinatura e gestão contratual.', 1 from public.trilhas where slug='sup' on conflict (slug) do nothing;
insert into public.trilhas (slug, nome, descricao, cor, cor2, ordem) values ('int', 'Integração', 'Primeiros passos para quem está chegando na Rottas.', '#1F63B8', '#3B8BE6', 2) on conflict (slug) do nothing;
insert into public.secoes (trilha_id, slug, nome, descricao, ordem) select id, 'int-boas', 'Boas-vindas', 'Cultura, estrutura e ferramentas do dia a dia.', 0 from public.trilhas where slug='int' on conflict (slug) do nothing;
insert into public.secoes (trilha_id, slug, nome, descricao, ordem) select id, 'int-seg', 'Segurança do trabalho', 'Normas e conduta no canteiro.', 1 from public.trilhas where slug='int' on conflict (slug) do nothing;

-- Como lançar uma medição de contrato
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Como lançar uma medição de contrato', 'video', 'pilula', 6, null, 'POP-ENG-014', 'Passo a passo para registrar o boletim de medição (BM) de um empreiteiro no ERP, conferir quantidades contra o contrato e enviar para aprovação do gestor da obra.', array['medição','boletim de medição','contratos','ERP']::text[], true, coalesce((select array_agg(id) from public.setores where nome = any(array['Engenharia de Obras','Planejamento']::text[])), '{}'), true, 70, 3, 0, 30, true, 'Excelência Operacional', '2026-08-12'::timestamptz
from public.secoes s where s.slug='eng-erp' and not exists (select 1 from public.conteudos where codigo='POP-ENG-014');
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Antes de lançar a medição, o que precisa ser conferido?', array['O saldo do contrato e as quantidades do BM','Apenas o valor total da nota fiscal','O cronograma de compras','Nada, o ERP valida sozinho']::text[], 0, 0 from public.conteudos where codigo='POP-ENG-014' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-014' and pq.ordem=0);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Quem aprova a medição depois do lançamento?', array['O fornecedor','O gestor da obra','O financeiro diretamente','O RH']::text[], 1, 1 from public.conteudos where codigo='POP-ENG-014' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-014' and pq.ordem=1);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Medição acima do saldo do contrato deve:', array['Ser lançada mesmo assim','Ser dividida em duas medições','Gerar solicitação de aditivo antes','Ser lançada como adiantamento']::text[], 2, 2 from public.conteudos where codigo='POP-ENG-014' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-014' and pq.ordem=2);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Em qual tela do ERP se lança o boletim de medição?', array['Contratos > Medições','Compras > Pedidos','Financeiro > Títulos','Estoque > Entradas']::text[], 0, 3 from public.conteudos where codigo='POP-ENG-014' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-014' and pq.ordem=3);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'O que acontece com a medição devolvida pelo gestor?', array['É excluída','Volta para correção com o comentário do gestor','Vai direto para pagamento','Fica bloqueada até o mês seguinte']::text[], 1, 4 from public.conteudos where codigo='POP-ENG-014' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-014' and pq.ordem=4);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Qual documento do empreiteiro acompanha a medição?', array['Memória de cálculo das quantidades','Contrato social','Certidão negativa de débitos','Nenhum']::text[], 0, 5 from public.conteudos where codigo='POP-ENG-014' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-014' and pq.ordem=5);
insert into public.faq (conteudo_id, pergunta, resposta, ordem) select id, 'Posso lançar medição retroativa?', 'Sim, até o fechamento do mês contábil. Depois disso, fale com a Controladoria para reabrir o período.', 0 from public.conteudos where codigo='POP-ENG-014' and not exists (select 1 from public.faq ff join public.conteudos cc on cc.id=ff.conteudo_id where cc.codigo='POP-ENG-014' and ff.ordem=0);
insert into public.faq (conteudo_id, pergunta, resposta, ordem) select id, 'O que faço se o item do BM não existe no contrato?', 'O item precisa entrar no contrato por aditivo. Veja o vídeo "Solicitando um aditivo contratual".', 1 from public.conteudos where codigo='POP-ENG-014' and not exists (select 1 from public.faq ff join public.conteudos cc on cc.id=ff.conteudo_id where cc.codigo='POP-ENG-014' and ff.ordem=1);

-- Solicitando um aditivo contratual
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Solicitando um aditivo contratual', 'video', 'pilula', 5, null, 'POP-ENG-021', 'Como abrir o pedido de aditivo de valor ou de prazo no ERP, anexar a memória de cálculo e acompanhar a aprovação.', array['aditivo','contratos','ERP','aprovação']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), true, 70, 2, 0, 30, true, 'Excelência Operacional', '2026-08-19'::timestamptz
from public.secoes s where s.slug='eng-erp' and not exists (select 1 from public.conteudos where codigo='POP-ENG-021');
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Qual documento é obrigatório anexar ao aditivo de valor?', array['Memória de cálculo','Foto da obra','Contrato social do fornecedor','Nenhum']::text[], 0, 0 from public.conteudos where codigo='POP-ENG-021' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-021' and pq.ordem=0);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Aditivo de prazo altera:', array['Somente o valor','A vigência do contrato','O CNPJ do fornecedor','O centro de custo']::text[], 1, 1 from public.conteudos where codigo='POP-ENG-021' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-021' and pq.ordem=1);
insert into public.faq (conteudo_id, pergunta, resposta, ordem) select id, 'Aditivo de valor e de prazo podem ir no mesmo pedido?', 'Podem. Marque os dois tipos no formulário e anexe a justificativa de cada um.', 0 from public.conteudos where codigo='POP-ENG-021' and not exists (select 1 from public.faq ff join public.conteudos cc on cc.id=ff.conteudo_id where cc.codigo='POP-ENG-021' and ff.ordem=0);

-- Consultando saldo de contrato
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Consultando saldo de contrato', 'video', 'pilula', 3, null, 'POP-ENG-015', 'Onde encontrar o saldo atualizado de um contrato, já descontadas as medições aprovadas e pendentes.', array['contratos','saldo','ERP','consulta']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Excelência Operacional', '2026-08-26'::timestamptz
from public.secoes s where s.slug='eng-erp' and not exists (select 1 from public.conteudos where codigo='POP-ENG-015');

-- Cadastro de fornecedor no ERP
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Cadastro de fornecedor no ERP', 'pdf', 'pilula', null, 6, 'POP-SUP-003', 'Procedimento operacional padrão completo, com a lista de documentos exigidos para homologar um fornecedor.', array['fornecedor','cadastro','ERP','POP']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Suprimentos', '2026-07-30'::timestamptz
from public.secoes s where s.slug='eng-erp' and not exists (select 1 from public.conteudos where codigo='POP-SUP-003');

-- Treinamento: novo BPM de medições
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Treinamento: novo BPM de medições', 'video', 'treinamento', 42, null, 'TRN-2026-07', 'Gravação do treinamento ao vivo (Teams, 14/08/2026) que apresentou o novo fluxo de aprovação de medições no BPM, com a sessão de perguntas no final.', array['BPM','medição','aprovação','treinamento gravado']::text[], true, coalesce((select array_agg(id) from public.setores where nome = any(array['Engenharia de Obras','Planejamento','Financeiro']::text[])), '{}'), true, 80, 5, 20, 30, true, 'Excelência Operacional', '2026-08-15'::timestamptz
from public.secoes s where s.slug='eng-bpm' and not exists (select 1 from public.conteudos where codigo='TRN-2026-07');
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'No novo fluxo, a medição segue do engenheiro para:', array['O financeiro','O coordenador da obra','O diretor','O fornecedor']::text[], 1, 0 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=0);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Qual o prazo de aprovação em cada etapa?', array['24 horas','48 horas','5 dias úteis','Não há prazo']::text[], 1, 1 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=1);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Uma medição reprovada volta para:', array['O início do fluxo, com o comentário do aprovador','O arquivo morto','O fornecedor diretamente','O RH']::text[], 0, 2 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=2);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Onde acompanhar o status da medição?', array['Por e-mail apenas','No painel "Minhas solicitações" do BPM','Na planilha da obra','No WhatsApp do coordenador']::text[], 1, 3 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=3);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'A partir de quando o fluxo antigo deixou de valer?', array['01/08/2026','01/09/2026','01/01/2027','Ainda vale']::text[], 1, 4 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=4);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Como delegar a aprovação durante as férias?', array['Passando a senha para um colega','Em Configurações > Delegação no BPM','Pedindo ao TI por e-mail','Não é possível delegar']::text[], 1, 5 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=5);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'O que o aprovador deve fazer ao reprovar uma medição?', array['Reprovar sem comentário','Registrar o motivo no comentário','Ligar para o fornecedor','Excluir a medição']::text[], 1, 6 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=6);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Qual etapa vem depois da aprovação do coordenador?', array['Validação do financeiro','Assinatura do fornecedor','Auditoria externa','Arquivamento']::text[], 0, 7 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=7);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Medições acima de qual valor precisam de aprovação da diretoria?', array['R$ 10 mil','R$ 50 mil','R$ 200 mil','Qualquer valor']::text[], 2, 8 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=8);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Onde ficam os anexos da medição no novo BPM?', array['Na aba Documentos da solicitação','Na pasta da obra no servidor','No e-mail do coordenador','Não há anexos']::text[], 0, 9 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-07' and pq.ordem=9);
insert into public.faq (conteudo_id, pergunta, resposta, ordem) select id, 'O fluxo antigo ainda funciona?', 'Não. Desde 01/09/2026 todas as medições passam pelo novo BPM.', 0 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.faq ff join public.conteudos cc on cc.id=ff.conteudo_id where cc.codigo='TRN-2026-07' and ff.ordem=0);
insert into public.faq (conteudo_id, pergunta, resposta, ordem) select id, 'Posso delegar a aprovação nas férias?', 'Sim, em Configurações > Delegação no próprio BPM, informando o período.', 1 from public.conteudos where codigo='TRN-2026-07' and not exists (select 1 from public.faq ff join public.conteudos cc on cc.id=ff.conteudo_id where cc.codigo='TRN-2026-07' and ff.ordem=1);

-- Fluxo de aprovação de aditivo no BPM
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Fluxo de aprovação de aditivo no BPM', 'video', 'pilula', 4, null, 'POP-ENG-022', 'O caminho do aditivo depois de solicitado: quem aprova, em que ordem e o que fazer quando é devolvido.', array['BPM','aditivo','aprovação']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), true, 70, 1, 0, 30, true, 'Excelência Operacional', '2026-08-28'::timestamptz
from public.secoes s where s.slug='eng-bpm' and not exists (select 1 from public.conteudos where codigo='POP-ENG-022');
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Aditivos acima de 10% do contrato exigem aprovação de:', array['Diretoria de engenharia','Somente o engenheiro','Fornecedor','Ninguém']::text[], 0, 0 from public.conteudos where codigo='POP-ENG-022' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-022' and pq.ordem=0);

-- Abrindo uma solicitação de compra
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Abrindo uma solicitação de compra', 'slides', 'pilula', null, 8, 'POP-SUP-010', 'Slides com o passo a passo para abrir a solicitação de compra no BPM, com prazos de antecedência por tipo de material.', array['BPM','compras','solicitação']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Suprimentos', '2026-09-02'::timestamptz
from public.secoes s where s.slug='eng-bpm' and not exists (select 1 from public.conteudos where codigo='POP-SUP-010');

-- Treinamento Mereo 2026: ciclo de metas
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Treinamento Mereo 2026: ciclo de metas', 'video', 'treinamento', 38, null, 'TRN-2026-05', 'Gravação do treinamento sobre o ciclo de metas 2026 no Mereo: cadastro, pesos, evidências e calendário de check-ins.', array['Mereo','metas','desempenho','treinamento gravado']::text[], true, coalesce((select array_agg(id) from public.setores where nome = any(array['Engenharia de Obras','Planejamento','Orçamentos','Qualidade']::text[])), '{}'), true, 70, 3, 15, 30, true, 'Gente & Gestão', '2026-06-10'::timestamptz
from public.secoes s where s.slug='eng-mereo' and not exists (select 1 from public.conteudos where codigo='TRN-2026-05');
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Quantas metas individuais no máximo por colaborador?', array['3','5','8','Sem limite']::text[], 1, 0 from public.conteudos where codigo='TRN-2026-05' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-05' and pq.ordem=0);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'A soma dos pesos das metas deve ser:', array['50%','100%','Livre','200%']::text[], 1, 1 from public.conteudos where codigo='TRN-2026-05' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-05' and pq.ordem=1);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Evidências devem ser anexadas:', array['Só no fim do ano','A cada check-in trimestral','Nunca','Pelo RH']::text[], 1, 2 from public.conteudos where codigo='TRN-2026-05' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-05' and pq.ordem=2);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Quem cadastra as metas da obra?', array['O coordenador da obra','Cada estagiário','O RH','O fornecedor']::text[], 0, 3 from public.conteudos where codigo='TRN-2026-05' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-05' and pq.ordem=3);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Com que frequência acontecem os check-ins?', array['Mensal','Trimestral','Anual','Não há check-in']::text[], 1, 4 from public.conteudos where codigo='TRN-2026-05' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-05' and pq.ordem=4);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Se você muda de obra no meio do ciclo:', array['As metas vão junto sem revisão','O novo coordenador revisa as metas em até 30 dias','O ciclo é cancelado','Nada muda']::text[], 1, 5 from public.conteudos where codigo='TRN-2026-05' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-05' and pq.ordem=5);
insert into public.faq (conteudo_id, pergunta, resposta, ordem) select id, 'Quem cadastra as metas da obra?', 'O coordenador cadastra as metas da obra; cada engenheiro desdobra as suas a partir delas.', 0 from public.conteudos where codigo='TRN-2026-05' and not exists (select 1 from public.faq ff join public.conteudos cc on cc.id=ff.conteudo_id where cc.codigo='TRN-2026-05' and ff.ordem=0);

-- Lançando resultado de indicador no Mereo
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Lançando resultado de indicador no Mereo', 'video', 'pilula', 4, null, 'POP-ENG-031', 'Como lançar o realizado do mês de um indicador e anexar a evidência.', array['Mereo','indicadores','evidência']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Excelência Operacional', '2026-07-08'::timestamptz
from public.secoes s where s.slug='eng-mereo' and not exists (select 1 from public.conteudos where codigo='POP-ENG-031');

-- Lendo o painel de indicadores da obra
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Lendo o painel de indicadores da obra', 'slides', 'pilula', null, 6, 'POP-ENG-032', 'O que significa cada indicador do painel da obra (IDP, IDC, avanço físico) e como agir quando sai da meta.', array['Mereo','indicadores','IDP','IDC']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Planejamento', '2026-07-15'::timestamptz
from public.secoes s where s.slug='eng-mereo' and not exists (select 1 from public.conteudos where codigo='POP-ENG-032');

-- Rodada de atualização orçamentária 2026.2
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Rodada de atualização orçamentária 2026.2', 'video', 'treinamento', 45, null, 'TRN-2026-09', 'Gravação do treinamento de abertura da rodada 2026.2: calendário, premissas de reajuste (INCC), responsabilidades por obra e entrega no ERP.', array['atualização orçamentária','INCC','premissas','treinamento gravado']::text[], true, coalesce((select array_agg(id) from public.setores where nome = any(array['Engenharia de Obras','Orçamentos','Planejamento']::text[])), '{}'), true, 70, 4, 20, 30, true, 'Orçamentos', '2026-09-05'::timestamptz
from public.secoes s where s.slug='eng-orc' and not exists (select 1 from public.conteudos where codigo='TRN-2026-09');
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Qual índice de reajuste é a premissa padrão da rodada?', array['IPCA','INCC','IGP-M','Selic']::text[], 1, 0 from public.conteudos where codigo='TRN-2026-09' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-09' and pq.ordem=0);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Quem valida a reprojeção antes da diretoria?', array['O fornecedor','O coordenador de orçamentos','O almoxarife','Ninguém']::text[], 1, 1 from public.conteudos where codigo='TRN-2026-09' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-09' and pq.ordem=1);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'A data limite de entrega da rodada 2026.2 é:', array['30/09','15/10','31/12','Não há data']::text[], 1, 2 from public.conteudos where codigo='TRN-2026-09' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-09' and pq.ordem=2);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Contratos com reajuste próprio devem usar:', array['Sempre o INCC','O índice previsto no contrato','O IPCA','Nenhum reajuste']::text[], 1, 3 from public.conteudos where codigo='TRN-2026-09' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-09' and pq.ordem=3);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Onde se registra uma exceção às premissas?', array['Na aba de premissas do template','Por WhatsApp','No Mereo','Não se registra']::text[], 0, 4 from public.conteudos where codigo='TRN-2026-09' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-09' and pq.ordem=4);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'A contingência da obra entra como:', array['Verba separada com justificativa','Diluída nos itens','Não entra','Só no fim da obra']::text[], 0, 5 from public.conteudos where codigo='TRN-2026-09' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-09' and pq.ordem=5);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'Quem é responsável pela reprojeção de cada obra?', array['O engenheiro da obra, com apoio de orçamentos','Só o diretor','O fornecedor','O financeiro']::text[], 0, 6 from public.conteudos where codigo='TRN-2026-09' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-09' and pq.ordem=6);
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'A rodada é entregue em qual sistema?', array['ERP','Mereo','BPM','Planilha por e-mail']::text[], 0, 7 from public.conteudos where codigo='TRN-2026-09' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='TRN-2026-09' and pq.ordem=7);
insert into public.faq (conteudo_id, pergunta, resposta, ordem) select id, 'Contratos com reajuste próprio usam INCC?', 'Não. Use o índice previsto no contrato e registre a exceção na aba de premissas.', 0 from public.conteudos where codigo='TRN-2026-09' and not exists (select 1 from public.faq ff join public.conteudos cc on cc.id=ff.conteudo_id where cc.codigo='TRN-2026-09' and ff.ordem=0);

-- Reprogramando o cronograma físico-financeiro
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Reprogramando o cronograma físico-financeiro', 'video', 'pilula', 7, null, 'POP-ENG-041', 'Como redistribuir o saldo a executar mês a mês depois da reprojeção.', array['cronograma','físico-financeiro','atualização orçamentária']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), true, 70, 1, 0, 30, true, 'Planejamento', '2026-09-09'::timestamptz
from public.secoes s where s.slug='eng-orc' and not exists (select 1 from public.conteudos where codigo='POP-ENG-041');
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'O saldo a executar é redistribuído a partir de qual mês?', array['O mês corrente','O primeiro mês da obra','O mês seguinte ao fechamento','Qualquer mês']::text[], 2, 0 from public.conteudos where codigo='POP-ENG-041' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='POP-ENG-041' and pq.ordem=0);

-- Template de premissas da rodada
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Template de premissas da rodada', 'pdf', 'pilula', null, 4, 'POP-ORC-002', 'Guia de preenchimento do template de premissas: índices, verbas, contingência e justificativas.', array['premissas','template','atualização orçamentária']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Orçamentos', '2026-09-05'::timestamptz
from public.secoes s where s.slug='eng-orc' and not exists (select 1 from public.conteudos where codigo='POP-ORC-002');

-- Como ler a curva S da obra
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Como ler a curva S da obra', 'slides', 'pilula', null, 7, 'POP-ENG-043', 'Leitura da curva S planejada x realizada e o que os desvios indicam.', array['curva S','planejamento','avanço físico']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Planejamento', '2026-09-12'::timestamptz
from public.secoes s where s.slug='eng-orc' and not exists (select 1 from public.conteudos where codigo='POP-ENG-043');

-- Prazos de compra por tipo de material
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Prazos de compra por tipo de material', 'video', 'pilula', 4, null, 'POP-SUP-011', 'Antecedência mínima para pedir aço, concreto, esquadrias e itens de acabamento.', array['compras','prazos','materiais']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Suprimentos', '2026-08-20'::timestamptz
from public.secoes s where s.slug='sup-compras' and not exists (select 1 from public.conteudos where codigo='POP-SUP-011');

-- Minuta padrão de empreitada
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Minuta padrão de empreitada', 'pdf', 'pilula', null, 12, 'POP-SUP-020', 'Cláusulas obrigatórias, retenções e garantias da minuta padrão.', array['contratos','minuta','empreitada']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Jurídico', '2026-08-01'::timestamptz
from public.secoes s where s.slug='sup-contratos' and not exists (select 1 from public.conteudos where codigo='POP-SUP-020');

-- Bem-vindo à Rottas
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Bem-vindo à Rottas', 'video', 'pilula', 8, null, 'INT-001', 'Nossa história, estrutura das áreas e como a engenharia se conecta com o resto da empresa.', array['integração','cultura']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), false, 70, 5, 0, 30, true, 'Gente & Gestão', '2026-05-02'::timestamptz
from public.secoes s where s.slug='int-boas' and not exists (select 1 from public.conteudos where codigo='INT-001');

-- Integração de segurança no canteiro
insert into public.conteudos (secao_id, titulo, tipo, formato, duracao_min, paginas, codigo, descricao, tags, obrigatorio, publico_setores, quiz_ativo, quiz_nota_min, quiz_sortear, quiz_tempo_min, quiz_espera_min, duvidas_ativas, autor, created_at)
select s.id, 'Integração de segurança no canteiro', 'slides', 'pilula', null, 9, 'SEG-004', 'EPIs obrigatórios, sinalização e conduta no canteiro de obras.', array['segurança','EPI','canteiro']::text[], false, coalesce((select array_agg(id) from public.setores where nome = any(array[]::text[])), '{}'), true, 80, 1, 0, 30, true, 'SESMT', '2026-05-02'::timestamptz
from public.secoes s where s.slug='int-seg' and not exists (select 1 from public.conteudos where codigo='SEG-004');
insert into public.perguntas_quiz (conteudo_id, enunciado, alternativas, correta, ordem) select id, 'O capacete é obrigatório:', array['Só em altura','Em toda a área do canteiro','Só para visitantes','Nunca']::text[], 1, 0 from public.conteudos where codigo='SEG-004' and not exists (select 1 from public.perguntas_quiz pq join public.conteudos cc on cc.id=pq.conteudo_id where cc.codigo='SEG-004' and pq.ordem=0);

